name: 'generate doxygen for gh-pges'

on:
  push:
    paths:
      - '**/*.cpp'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: doxygen testing
        uses: mattnotmitt/doxygen-action@v1.9.2
        with:
          working-directory: 'docs/'
          doxyfile-path: 'Doxygen/Doxyfile.in'
          
      - name: show changes
        run: |
          git status
      
      - name: add untracked files
        run: |
          git add .
          
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
